name: Unified Multi-Account Workflow (Optimized Mode)

on:
  workflow_dispatch:
    inputs:
      repo_prefix:
        description: 'Prefix nama repository (contoh: rixz)'
        default: 'rixz'
      repo_count:
        description: 'Jumlah repository per akun'
        default: 1
      total_commits:
        description: "Jumlah total commit per akun"
        default: 1650
      total_days:
        description: "Jumlah hari pembagian commit"
        default: 365
      total_prs:
        description: "Jumlah Pull Request per akun"
        default: 1
      total_issues:
        description: "Jumlah Issue per akun"
        default: 1
      target_repo:
        description: "Repository utama (contoh: username/activity-hub)"
        default: "vegeta888/hapus"

jobs:
  unified:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 8   # 🔥 Naikkan paralel dari 5 → 8 (lebih cepat, masih aman)
      matrix:
        include:
          - account: vegeta888
            email: 19150937+vegeta888@users.noreply.github.com
            token_secret: PAT1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Delay antar akun biar gak nabrak API
      - name: Delay before start
        run: |
          DELAY=$((10 + RANDOM % 15))
          echo "🕒 Delay $DELAY detik sebelum memulai akun ${{ matrix.account }}..."
          sleep $DELAY

      # === STEP 1: Clone target repo & setup git identity ===
      - name: Clone target repo
        env:
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO repo
          cd repo
          git config user.name "${{ matrix.account }}"
          git config user.email "${{ matrix.email }}"
          echo "✅ Git identity set untuk ${{ matrix.account }}"

      # === STEP 2: Generate commits lebih cepat ===
      - name: Generate commits
        env:
          TOTAL_COMMITS: ${{ github.event.inputs.total_commits }}
          TOTAL_DAYS: ${{ github.event.inputs.total_days }}
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          cd repo
          mkdir -p logs
          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          START_DATE=$(date -d "$TOTAL_DAYS days ago" +%Y-%m-%d)
          echo "📊 $TOTAL_COMMITS commits akan dibuat selama $TOTAL_DAYS hari..."

          for ((day=0; day<TOTAL_DAYS; day++)); do
            DATE_STR=$(date -d "$START_DATE +$day days" +%Y-%m-%d)
            for ((i=1; i<=COMMITS_PER_DAY; i++)); do
              echo "Commit $i oleh ${{ matrix.account }} pada $DATE_STR" >> logs/${{ matrix.account }}_$day.txt
              git add logs/${{ matrix.account }}_$day.txt
              GIT_COMMITTER_DATE="$DATE_STR 12:00:00" \
              GIT_AUTHOR_DATE="$DATE_STR 12:00:00" \
              git commit -m "Auto commit $i by ${{ matrix.account }}" || true
            done
          done

          echo "🚀 Push commits..."
          for attempt in {1..3}; do
            git push --force https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO HEAD:main && break || sleep 3
          done
          echo "✅ Commits pushed!"

      # === STEP 3: Create Pull Requests & Issues (Optimized Delay) ===
      - name: Create PRs & Issues
        env:
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
          TOTAL_PRS: ${{ github.event.inputs.total_prs }}
          TOTAL_ISSUES: ${{ github.event.inputs.total_issues }}
        run: |
          cd repo
          echo "🔀 Membuat $TOTAL_PRS PR dan $TOTAL_ISSUES Issue di $TARGET_REPO..."

          pr_success=0
          issue_success=0

          # === Buat Pull Requests lebih cepat (delay kecil tapi aman) ===
          for i in $(seq 1 $TOTAL_PRS); do
            branch="auto-${{ matrix.account }}-pr-$i-$(date +%s)"
            echo "Pull request #$i by ${{ matrix.account }}" > pr_${{ matrix.account }}_$i.txt
            git checkout -B $branch
            git add pr_${{ matrix.account }}_$i.txt
            git commit -m "PR otomatis #$i oleh ${{ matrix.account }}" || true
            git push -f https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO HEAD:$branch
            gh pr create \
              --title "PR #$i dari ${{ matrix.account }}" \
              --body "PR otomatis oleh ${{ matrix.account }}" \
              --base main --head $branch \
              --repo $TARGET_REPO >/dev/null 2>&1 && pr_success=$((pr_success + 1)) || true
            sleep 0.6  # 🔥 delay dipangkas dari 2s → 0.6s
          done

          # === Buat Issues lebih cepat ===
          for i in $(seq 1 $TOTAL_ISSUES); do
            gh issue create \
              --title "Issue #$i dari ${{ matrix.account }}" \
              --body "Auto-generated issue $i oleh ${{ matrix.account }}" \
              --repo $TARGET_REPO >/dev/null 2>&1 && issue_success=$((issue_success + 1)) || true
            sleep 0.4  # 🔥 delay dipangkas dari 1s → 0.4s
          done

          echo ""
          echo "📊 Summary untuk ${{ matrix.account }}"
          echo "✅ PR sukses: $pr_success"
          echo "✅ Issue sukses: $issue_success"

